spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer

batch-meta:
  datasource:
    url: ${BATCH_META_DB_URL}
    username: ${BATCH_META_DB_USER}
    password: ${BATCH_META_DB_PASSWORD}

batch:
  docker:
    web-url: "https://hub.docker.com"
    api-url: "https://hub.docker.com/v2"
    username: ${DOCKERHUB_USER}
    password: ${DOCKERHUB_PASSWORD}
  kafka:
    topic: ${KAFKA_TOPIC}
